/**
 * Wiredcraft Backend Test
 * Wiredcraft Backend Test
 *
 * OpenAPI spec version: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import OkResponse from '../model/OkResponse';
import RelationRequest from '../model/RelationRequest';
import RelationResponse from '../model/RelationResponse';

/**
* UserLink service.
* @module api/UserLinkApi
* @version v0.0.1
*/
export default class UserLinkApi {

    /**
    * Constructs a new UserLinkApi. 
    * @alias module:api/UserLinkApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the followUser operation.
     * @callback module:api/UserLinkApi~followUserCallback
     * @param {String} error Error message, if any.
     * @param {module:model/OkResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * follow a user
     * @param {module:api/UserLinkApi~followUserCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/OkResponse}
     */
    followUser(body, callback) {
      let postBody = body;


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = OkResponse;

      return this.apiClient.callApi(
        '/userlink/follow', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getFollowers operation.
     * @callback module:api/UserLinkApi~getFollowersCallback
     * @param {String} error Error message, if any.
     * @param {module:model/RelationResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get the followers list of user
     * @param {module:api/UserLinkApi~getFollowersCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/RelationResponse}
     */
    getFollowers(id, callback) {
      let postBody = null;


      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = RelationResponse;

      return this.apiClient.callApi(
        '/userlink/follower/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getFollowings operation.
     * @callback module:api/UserLinkApi~getFollowingsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/RelationResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get the following list of user
     * @param {module:api/UserLinkApi~getFollowingsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/RelationResponse}
     */
    getFollowings(id, callback) {
      let postBody = null;


      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = RelationResponse;

      return this.apiClient.callApi(
        '/userlink/following/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the unfollowUser operation.
     * @callback module:api/UserLinkApi~unfollowUserCallback
     * @param {String} error Error message, if any.
     * @param {module:model/OkResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * unfollow a user
     * @param {module:api/UserLinkApi~unfollowUserCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/OkResponse}
     */
    unfollowUser(body, callback) {
      let postBody = body;


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = OkResponse;

      return this.apiClient.callApi(
        '/userlink/unfollow', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }


}
