/**
 * Wiredcraft Backend Test
 * Wiredcraft Backend Test
 *
 * OpenAPI spec version: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import OkResponse from '../model/OkResponse';
import RelationRequest from '../model/RelationRequest';

/**
* UserLik service.
* @module api/UserLikApi
* @version v0.0.1
*/
export default class UserLikApi {

    /**
    * Constructs a new UserLikApi. 
    * @alias module:api/UserLikApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the followUser operation.
     * @callback module:api/UserLikApi~followUserCallback
     * @param {String} error Error message, if any.
     * @param {module:model/OkResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * follow a user
     * @param {module:api/UserLikApi~followUserCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/OkResponse}
     */
    followUser(body, callback) {
      let postBody = body;


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = OkResponse;

      return this.apiClient.callApi(
        '/userlink/follow', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the unfollowUser operation.
     * @callback module:api/UserLikApi~unfollowUserCallback
     * @param {String} error Error message, if any.
     * @param {module:model/OkResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * unfollow a user
     * @param {module:api/UserLikApi~unfollowUserCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/OkResponse}
     */
    unfollowUser(body, callback) {
      let postBody = body;


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = OkResponse;

      return this.apiClient.callApi(
        '/userlink/unfollow', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }


}
