/**
 * Wiredcraft Backend Test
 * Wiredcraft Backend Test
 *
 * OpenAPI spec version: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import NearbyResponse from './model/NearbyResponse';
import OkResponse from './model/OkResponse';
import User from './model/User';
import UserGeo from './model/UserGeo';
import UserResponse from './model/UserResponse';
import UserApi from './api/UserApi';
import UserGeoApi from './api/UserGeoApi';


/**
* Wiredcraft_Backend_Test.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var WiredcraftBackendTest = require('index'); // See note below*.
* var xxxSvc = new WiredcraftBackendTest.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new WiredcraftBackendTest.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new WiredcraftBackendTest.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new WiredcraftBackendTest.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v0.0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The NearbyResponse model constructor.
     * @property {module:model/NearbyResponse}
     */
    NearbyResponse,

    /**
     * The OkResponse model constructor.
     * @property {module:model/OkResponse}
     */
    OkResponse,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The UserGeo model constructor.
     * @property {module:model/UserGeo}
     */
    UserGeo,

    /**
     * The UserResponse model constructor.
     * @property {module:model/UserResponse}
     */
    UserResponse,

    /**
    * The UserApi service constructor.
    * @property {module:api/UserApi}
    */
    UserApi,

    /**
    * The UserGeoApi service constructor.
    * @property {module:api/UserGeoApi}
    */
    UserGeoApi
};
