# Generated by Django 3.1.7 on 2021-02-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appuser',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=80)),
                ('dob', models.DateField()),
                ('address', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField()),
            ],
            options={
                'ordering': ['createdAt'],
            },
        ),
    ]
