/**
 * Wiredcraft Backend Test
 * Wiredcraft Backend Test
 *
 * OpenAPI spec version: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';


/**
* The NearbyResponse model module.
* @module model/NearbyResponse
* @version v0.0.1
*/
export default class NearbyResponse {
    /**
    * Constructs a new <code>NearbyResponse</code>.
    * @alias module:model/NearbyResponse
    * @class
    */

    constructor() {
        
        
        
        
        
    }

    /**
    * Constructs a <code>NearbyResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/NearbyResponse} obj Optional instance to populate.
    * @return {module:model/NearbyResponse} The populated <code>NearbyResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NearbyResponse();
                        
            
            
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Number');
            }

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {Number} code
    */
    'code' = undefined;
    /**
    * @member {Array.<String>} data
    */
    'data' = undefined;







}

