/**
 * Wiredcraft Backend Test
 * Wiredcraft Backend Test
 *
 * OpenAPI spec version: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';


/**
* The UserLink model module.
* @module model/UserLink
* @version v0.0.1
*/
export default class UserLink {
    /**
    * Constructs a new <code>UserLink</code>.
    * @alias module:model/UserLink
    * @class
    */

    constructor() {
        
        
        
        
        
    }

    /**
    * Constructs a <code>UserLink</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UserLink} obj Optional instance to populate.
    * @return {module:model/UserLink} The populated <code>UserLink</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserLink();
                        
            
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }

            if (data.hasOwnProperty('link')) {
                obj['link'] = ApiClient.convertToType(data['link'], ['String']);
            }
        }
        return obj;
    }

    /**
    * user id, shall be a string of uuid v4, length limit 36
    * @member {String} id
    */
    'id' = undefined;
    /**
    * @member {Array.<String>} link
    */
    'link' = undefined;







}

