let data = [{"name":"Captain James T. Kirk",
            "dob":"1964-09-22T09:06:48.743Z",
            "address":"USS Enterprise",
            "description":"Starfleet captain extraodinaire"},
            {"name":"Commander Spock",
             "dob":"1934-07-22T09:06:48.743Z",
             "address":"USS Enterprise",
             "description":"Vulcan first officer"},
            {"name":"Captain Benjamin Sisko",
             "dob":"1974-08-20T09:06:48.743Z",
             "address":"Deep Space Nine",
             "description":"Commands DS9 and is the Emmissary of the Prophets"},
            {"name":"Lieutenant Nog",
             "dob":"1999-08-19T16:00:00.000Z",
             "address":"Deep Space Nine",
             "description":"First Ferengi in Starfleet"},
            {"name":"Seven of Nine",
             "dob":"1992-08-23T00:00:00.000Z",
             "address":"USS Voyager",
             "description":"Once a member of the Borg collective"},
             {"name":"Ensign Harry Kim",
              "dob":"1994-06-11T00:00:00.000Z",
              "address":"USS Voyager",
              "description":"Not promoted in over 5 years"},
             {"name":"Captain Edward Jellico",
              "dob":"1949-02-02T00:00:00.000Z",
              "address":"USS Enterprise",
              "description":"Not a very well liked captain"},
              {"name":"Lieutenant Exri Dax",
               "dob":"1997-05-19T16:00:00.000Z",
               "address":"Deep Space Nine",
               "description":"A Dax but not the Dax we wanted, but still very likeable."},
              {"name":"Lt. Cmdr. Worf",
               "dob":"1980-07-16T16:00:00.000Z",
               "address":"USS Enterprise",
               "description":"Lucky enough to marry the Dax we all wanted to marry"},
              {"name":"Lt. Cmdr. Deanna Troi",
               "dob":"1982-04-07T04:23:36.104Z",
               "address":"USS Enterprise",
               "description":"Ship's counselor who serves the greater good"},
            {"name":"Captain Malcom Reynolds",
             "dob":"1985-07-22T09:06:48.743Z",
             "address":"Serenity",
             "description":"Former Browncoat that's almost always aiming to get into some trouble"},
            ]

module.exports = data;
