const restful = require('node-restful');

const { mongoose } = restful;

function User() {

}

/*
  User Schema
  Note: unique id will be generated by mongoose
*/
User.schema = new mongoose.Schema({
  name: { type: String, required: true },
  dob: { type: Date, required: true },
  address: { type: String },
  description: { type: String },
}, {
  timestamps: {
    createdAt: 'created_at',
    updatedAt: 'updated_at',
  },
});

User.model = mongoose.model('user', User.schema);

module.exports = restful.model('Users', User.schema);
