'use strict'

const mongoose = require('mongoose')

function User() {

}

/*
  User Schema
  Note: unique id will be generated by mongoose
*/
User.schema = new mongoose.Schema({
	name: { type: String, required: true },
	dob: { type: Date, required: true },
	address: { type: String },
	description: { type: String },
	created_at: { type: Date, default: Date.now }
});

User.model = mongoose.model('user', User.schema);

module.exports = User
